### ISSUE TITLE
Jamf's URL's http is getting printed after invitation ID when going to print the second invitation

### ISSUE THREAD

**Issue by Mollahasifahmed** [kylejericson/Jamf-Enrollment-URL-Generator#1]
My Jamf URL's https is getting copied after invitation when it is going to print the second invitation, can you please fix it, it would more precise.

**Comment by kylejericson** [comment]
Can you share a screenshot of this example?

**Comment by Mollahasifahmed** [comment]
I shared you in LinkedIn chat, please check as it is showing my company's Jamf URL

**Comment by Mollahasifahmed** [comment]
If possible, please do in such a way that it will copy the info in MS share point rather than copying in clipboard.

**Comment by kylejericson** [comment]
I tested and the url is only getting copied once. Closing this issue out.
